Feature/custom logging module
stikkireddy/mlflow-extensions pull request #42
Opened 2024-09-11 13:11 UTC by natefleming

This PR adds supports for rolling logs and periodic uploading to Databricks volumes based on file size or duration.

This implementation uses a custom logging.handler.Handler implementation as well as the "structlog" library

* By default logs are rolled after 1 hour OR 1MB and 5 local copies are kept. All rolled over logs are uploaded 
* initialize_logging(...) - Should be called once to initialize 
* Files are uploaded with the jsonl extension
* Integrates StructLog with Standard Logging allowing external log messages to be captured
* get_logger(...) - This factory will inspect the call stack to determine a log name if not provided

StructLog allows for arbitrary key value pairs to be provided in log messages. These will all result in table columns

Example Usage with Defaults (rollover after 1 hour OR 1 MB file size)

```python

import logging
from mlflow_extensions.log import Logger, LogLevel, get_logger, initialize_logging
from mlflow_extensions.log.handlers import (
    rotating_volume_handler,
)

# Optional stdout Handler for tee'd output
stdout_handler: logging.Handler = logging.StreamHandler(sys.stdout)

volume_handler: logging.Handler = rotating_volume_handler(
    "test.log", "/Volumes/nfleming/default/logs",
)

initialize_logging(level=LogLevel.INFO, handlers=[stdout_handler, volume_handler])

logger: Logger = get_logger()
logger.debug("This is the message", foo="bar", baz="qux")
logger.info("This is the message", foo="bar", baz="qux")
logger.warning("This is the message", foo="bar", baz="qux")
logger.critical("This is the message", foo="bar", baz="qux")
logger.critical("This is the message", foo="bar", baz="qux")
logger.critical("This is the message", foo="bar", baz="qux")
```

2024-09-11 15:07 UTC, natefleming commented
Example Message:

```json
{"message": "This is the message", "taskName": null, "foo": "bar", "baz": "qux", "level": "debug", "logger": "__main__", "host": "W7633NGQKK", "ip": "143.244.220.150", "version": "0.10.1.dev9+gb58224f.d20240910", "timestamp": "2024-09-11T15:05:19.032372Z"}
```

2024-09-11 17:00 UTC, stikkireddy requested changes

2024-09-11 17:01 UTC, stikkireddy commented
> Should the catalog, schema and volume be created if they don't exist?

no i dont think we should create anything, or delete anything on behalf of the user like schema or catalog. we should just error gracefully during deployment. and ask the user to consciously do it.

2024-09-11 20:56 UTC, natefleming commented on mlflow_extensions/log/handlers.py
> +        from mlflow.utils.databricks_utils import get_databricks_host_creds
Thanks for the suggestions.

I put an import guard around the mlflow stuff (I think that function is deprecated anyway) and it prefers env variables.

I also added configuration of the volume through env vars.

The environment variables use to determine volume path are also logged as fields the event messages

Does something like this work?


```python
def _get_volume_path(volume_path: Optional[str]) -> Optional[str]:
    volume_path = volume_path or os.environ.get("LOGGING_VOLUME_PATH")
    if volume_path is None:
        volume: str = os.environ.get("LOGGING_VOLUME")
        volume_path: str = _full_volume_name_to_path(volume)
        model_name: str = os.environ.get("LOGGING_MODEL_NAME")
        endpoint_id: str = os.environ.get("LOGGING_ENDPOINT_ID")
        run_id: str = os.environ.get("LOGGING_RUN_ID")

        if volume_path is not None:
            volume_path = "/".join(
                [
                    x
                    for x in [volume_path, model_name, endpoint_id, run_id]
                    if x is not None
                ]
            )

    return volume_path
```

```python
def _get_databricks_host_creds(
    databricks_host: Optional[str], databricks_token: Optional[str]
) -> Tuple[str, str]:
    if databricks_host is None or databricks_token is None:
        try:
            from mlflow.utils.databricks_utils import get_databricks_host_creds

            databricks_host = os.environ.get(
                "DATABRICKS_HOST", get_databricks_host_creds().host
            )
            databricks_token = os.environ.get(
                "DATABRICKS_TOKEN", get_databricks_host_creds().token
            )
        except ImportError:
            databricks_host = os.environ.get("DATABRICKS_HOST")
            databricks_token = os.environ.get("DATABRICKS_TOKEN")

    return databricks_host, databricks_token
```

2024-09-12 21:55 UTC, stikkireddy commented
i will try to close this and the other PR out by tomorrow. This log rotation will be helpful also for lakehouse apps :D. Ideally we can reuse most of it as a one off file.

2024-09-12 21:59 UTC, natefleming commented
Sounds good. I hacked on it a bit today. I'm not quite sure where the best place to integrate it. I also think there might be a bug in filtering std logs but it should be close

2024-09-13 19:48 UTC, stikkireddy approved these changes
LGTM

2024-09-13 19:50 UTC, merged